# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
